[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_toml = "0.10"

[dependencies.clap]
git = "https://github.com/clap-rs/clap.git"
rev = "v3.0.0-rc.1"
features = ["derive"]
