[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prettytable-rs = "^0.8"

[dependencies.clap]
git = "https://github.com/clap-rs/clap.git"
rev = "v3.0.0-rc.7"
features = ["derive"]
