[alias]
xtask = "run --package xtask --"

[target.thumbv8m.main-none-eabi]
# runner = "qemu-system-arm -M mps2-an521 -semihosting -serial stdio -display none -d in_asm,int,exec,cpu,guest_errors,unimp -kernel"
runner = "qemu-system-arm -M mps2-an521 -semihosting -serial stdio -display none -kernel"
linker = "scripts/linker.py"
