[build]
target = "thumbv8m.main-none-eabi"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[target.thumbv8m.main-none-eabi]
runner = "qemu-system-arm -M mps2-an521 -semihosting -serial stdio -display none -kernel"

[unstable]
build-std = ["core", "compiler_builtins"]
